// Generated by scripts/generate-baked-artifacts.ts. Do not edit.
import type { rendererStagePlan } from './pipeline';

export const BAKED_POST_PLAN = [
    {
        id: 'post:god-rays:0',
        kind: 'god-rays',
        label: 'post:god-rays #1',
    },
    {
        id: 'post:bloom:0',
        kind: 'bloom',
        label: 'post:bloom #1',
    },
    {
        id: 'post:glow:0',
        kind: 'glow',
        label: 'post:glow #1',
    },
    {
        id: 'post:chromatic-aberration:0',
        kind: 'chromatic-aberration',
        label: 'post:chromatic-aberration #1',
    },
] as const satisfies ReturnType<typeof rendererStagePlan>;
export const BAKED_POST_PARAMETERS = [
    1, 0, 7950, 0, 0, 0, -0.01, 0, 0, 1, -100, 3, 0, 1, 0, -2, 64, 1, 0.27, 0.32, 1.6, 1.51, 1, 0.15, 0.97, 12, 1, 0.01,
    0.1, 0.17, 0.015, 0.5, 3, 3, 1, 1, 0, 0, 0, 0, 1, 0, 8, 0.7, 0, 1.92, 17, -0.64, 1.6, 0, 2, 7, 6, 0.98, 0, 2, 8.5,
    0, 0, 0.16, 8, 0.1, 0, 2, 13, 32, 6, 0.95, 0, 1.1, 5, 0, 1, 0, 0, 0, 0, 0.19, 32, 0, 0.299, 31, 0, 50, 2.5, 32, 0,
    0.117, 1.3, 0, 0, 30, 1, 0, 0, 0, 0, 1, 4, 0, 0.52, 36, 0, 0.004, 93, 0, 2, 0.25,
];
