import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { format, resolveConfig } from 'prettier';
import settingsDocument from '../src/lib/default-settings.json';
import { composeAdjustmentLut } from '../src/lib/adjustments';
import { leadingAdjustmentRegion, rendererStagePlan, type ColourEffect, type PostEffect } from '../src/lib/pipeline';
import type { ShaderParameters } from '../src/lib/renderer';
import { POST_PARAMETER_SCHEMA } from '../src/lib/renderer';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const settings = settingsDocument.settings as unknown as {
    parameters: ShaderParameters;
    colour: ColourEffect[];
    post: PostEffect[];
};
const lut = composeAdjustmentLut(leadingAdjustmentRegion(settings.colour));
const binary = Buffer.from(lut.buffer, lut.byteOffset, lut.byteLength);
const lutPath = resolve(root, 'static/baked-adjustment-lut.bin');
mkdirSync(dirname(lutPath), { recursive: true });
writeFileSync(lutPath, binary);

const plan = rendererStagePlan(settings.post, settings.parameters);
const postParameters = POST_PARAMETER_SCHEMA.map(({ key }) => settings.parameters[key]);
const planPath = resolve(root, 'src/lib/baked-post-plan.generated.ts');
const generatedPlan =
    `// Generated by scripts/generate-baked-artifacts.ts. Do not edit.\n` +
    `import type { rendererStagePlan } from './pipeline';\n\n` +
    `export const BAKED_POST_PLAN = ${JSON.stringify(plan, null, 4)} as const satisfies ReturnType<typeof rendererStagePlan>;\n` +
    `export const BAKED_POST_PARAMETERS = ${JSON.stringify(postParameters)};\n`;
writeFileSync(
    planPath,
    await format(generatedPlan, { ...(await resolveConfig(planPath, { editorconfig: true })), parser: 'typescript' }),
);
console.log(`generated ${binary.byteLength} byte LUT and ${plan.length} post stages`);
