// Generated by scripts/generate-baked-artifacts.ts. Do not edit.
import type { rendererStagePlan } from './pipeline';

export const BAKED_POST_PLAN = [] as const satisfies ReturnType<typeof rendererStagePlan>;
export const BAKED_POST_PARAMETERS = [
    1, 0, 6500, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0.75, 0.25, 0, 0, 64, 1, 0.75, 0.25, 0, 0.6, 1, 0, 0.08, 0, 0, 0.35, 0, 0, 0,
    1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 8, 0.7, 0, 0, 24, 0, 0.8, 0, 0, 12, 6, 0.8, 0, 0, 8, 0.7, 0, 0, 4, 0.7, 0, 0, 8,
    16, 6, 0.8, 0, 0, 1, 0, 0, 0.3, 0.3, 0.2, 0, 0, 12, 0, 0, 12, 0, 0, 0, 12, 0, 0, 1, 0, 0, 30, 1, 0, 0, 0, 0, 0, 6,
    0, 0, 16, 0, 0, 120, 1, 4, 1,
];
