name: '🐛 Bug Report'
description: Create a new ticket for a bug.
title: '🐛 - <title>'
labels: ['bug']
body:
  - type: textarea
    id: summary
    attributes:
      label: 'Summary'
      description: Please describe what happened
      placeholder: A clear and concise description of what happened.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 'Expected Behaviour'
      description: Please describe what you expected to happen
      placeholder: A clear and concise description of what you think should have happened.
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: 'Reproduction steps'
      description: Please enter detailed steps for how the issue can be reproduced
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: input
    id: reprod-url
    attributes:
      label: 'Reproduction URL'
      description: Please enter your GitHub URL to provide a reproduction of the issue
      placeholder: ex. https://github.com/USERNAME/REPO-NAME
    validations:
      required: false
  - type: textarea
    id: screenshot
    attributes:
      label: 'Screenshots'
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: 'Browsers'
      description: What browsers are you seeing the problem on ?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera (GX)
        - Vivaldi
        - Other
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: 'OS'
      description: What is the impacted environment ?
      multiple: true
      options:
        - Windows
        - Linux
        - macOS
        - iOS / iPadOS
        - Android
        - Other
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 'Logs'
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: false
