blank_issues_enabled: false
contact_links:
  - name: "Report a Security Vulnerability or Risk"
    url: "https://github.com/mia-cx"
    about: "If you find a dangerous Security Vulnerability, please email us in stead."
  - name: "Get a Quote"
    url: "https://mia.cx/hiring"
    about: "Hire us for your project"
  - name: "Job Opportunities"
    url: "https://mia.cx/careers"
    about: "Work with or at mia.cx"